# Generated by Django 2.0.6 on 2018-07-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firebase', '0002_auto_20180701_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizes',
            name='section',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='quizes',
            name='subject',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='quizes',
            name='Quiz_Date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='quizes',
            name='Quiz_Topic',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
