# Generated by Django 2.0.6 on 2018-07-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firebase', '0004_auto_20180706_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=75)),
                ('subject', models.CharField(max_length=50)),
                ('suggestion', models.CharField(max_length=150)),
            ],
        ),
    ]
