# Generated by Django 2.0.7 on 2018-08-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firebase', '0005_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserToken', models.CharField(max_length=50)),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
            ],
        ),
    ]
