# Generated by Django 2.0.7 on 2018-08-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firebase', '0006_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='UserType',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
