# Generated by Django 2.0.7 on 2018-08-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firebase', '0009_remove_accounts_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
