# Generated by Django 2.1.1 on 2018-09-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firebase', '0011_remove_accounts_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
